### ISSUE TITLE
Package

### ISSUE THREAD

**Issue by libertesedamatrix** [n1ghtw0lff/YTubevideoBot#2]
O Pacote YtAudioBot não existe ou não está disponível no npmjs, será que poderia disponibilizalo ou adicionar o pacote?
package.json

**Comment by je4ngomes** [comment]
@foradamatrix O YtAudioBot não é um projeto de minha autoria.

**Comment by libertesedamatrix** [comment]
> @foradamatrix O YtAudioBot não é um projeto de minha autoria.

está em desenvolvimento por outra pessoa? ou se tiver pode me passar?

**Comment by je4ngomes** [comment]
> > @foradamatrix O YtAudioBot não é um projeto de minha autoria.
> 
> está em desenvolvimento por outra pessoa? ou se tiver pode me passar?

Quando eu estava desenvolvendo o mesmo, eu tentei descobrir qual o método eles utilizarão para realizar a extração do áudio, mas sem sucesso...
