### ISSUE TITLE
TypeError: Cannot read property 'filter' of undefined

### ISSUE THREAD

**Issue by kevinmahrous** [n1ghtw0lff/YTubevideoBot#3]
I am using code but I am get 
```
TypeError: Cannot read property 'filter' of undefined
    at formatResults (C:\Users\Windows\Downloads\New Folder\actions\inline.js:10:42)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by kevinmahrous** [comment]
@jeanjs

**Comment by je4ngomes** [comment]
> I am using code but I am get
> 
> ```
> TypeError: Cannot read property 'filter' of undefined
>     at formatResults (C:\Users\Windows\Downloads\New Folder\actions\inline.js:10:42)
>     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> ```

Hi, sorry for not replying sooner. It's been a while since i've worked on this project. The error mentioned might be due to the library update having some breaking changes to the current code.

**Comment by kevinmahrous** [comment]
> > I am using code but I am get
> > ```
> > TypeError: Cannot read property 'filter' of undefined
> >     at formatResults (C:\Users\Windows\Downloads\New Folder\actions\inline.js:10:42)
> >     at processTicksAndRejections (node:internal/process/task_queues:94:5)
> > ```
> 
> Hi, sorry for not replying sooner. It's been a while since i've worked on this project. The error mentioned might be due to the library update having some breaking changes to the current code.

Sorry for late reply. Thank you for your reply. Your code is working very well. The problem was from my Youtube API Quote (The quote has been exceed) So when I changed my API to new one. The code worked. Thank you and I hope you continue to update repository with new update. Thank you. :)
